# Generated by Django 4.2.11 on 2024-04-11 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mangodschango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
